name: CI 

on:
  push:
    branches: [master]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: short
  CARGO_TERM_COLOR: always

jobs:
  # Check if code compiles.
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- run: rustup update stable && rustup default stable
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo check
        run: cargo check --all --examples --tests --benches

  # Check code style.
  fmt:
    name: cargo fmt
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- run: rustup update stable && rustup default stable
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --all -- --check

  # Check warnings.
  clippy:
    name: cargo clippy
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      #- run: rustup update stable && rustup default stable
      - name: Install Rust ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --examples --tests --benches

  # Check docs.
  docs:
    name: cargo doc
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- run: rustup update stable && rustup default stable
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo doc
        run: cargo doc --no-deps --all-features

  # Run test againts different systems.
  test:
    name: "cargo test (${{ matrix.toolchain }} on ${{ matrix.os }})"
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable, beta, nightly]
        include:
          - os: windows-latest
            toolchain: stable
          - os: macos-latest
            toolchain: stable
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      #- run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: "Install Rust ${{ matrix.toolchain }}"
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo test
        run: cargo test
